name: Reolink P2P Test
version: "0.1.2"
slug: reolink_p2p_test
description: Testet Reolink UID/P2P mit PyNeolink
url: https://github.com/weide-git/ha-reolink-cloud

arch:
  - amd64

startup: application
boot: manual
init: false

options:
  uid: "9527000KLBT71M83"
  username: "admin"
  password: ""

schema:
  uid: str
  username: str
  password: password
