name: "Reolink P2P Raw UDP Test"
version: "0.2.2"
slug: "reolink_p2p_raw_test"
description: "Direkter Reolink P2P UDP/H264 Test mit PyNeolink"
url: "https://github.com/weide-git/ha-reolink-cloud"
arch:
  - amd64
startup: application
boot: manual
init: false
options:
  uid: "9527000KLBT71M83"
  username: "admin"
  password: ""
schema:
  uid: str
  username: str
  password: password
